export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED';

export const FETCH_MY_COMMENTS = 'FETCH_MY_COMMENTS';
export const FETCH_MY_COMMENTS_SUCCESS = 'FETCH_MY_COMMENTS_SUCCESS';
export const FETCH_MY_COMMENTS_FAILED = 'FETCH_MY_COMMENTS_FAILED';

export const FETCH_NEW_COMMENTS = 'FETCH_NEW_COMMENTS';
export const FETCH_NEW_COMMENTS_SUCCESS = 'FETCH_NEW_COMMENTS_SUCCESS';
export const FETCH_NEW_COMMENTS_FAILED = 'FETCH_NEW_COMMENTS_FAILED';

export const FETCH_TARIFFS = 'FETCH_TARIFS';
export const FETCH_TARIFFS_SUCCESS = 'FETCH_TARIFFS_SUCCESS';
export const FETCH_TARIFFS_FAILED = 'FETCH_TARIFFS_FAILED';


export const FETCH_TASK_COMMENTS_LIST = 'FETCH_TASK_COMMENTS_LIST';
export const FETCH_TASK_COMMENTS_LIST_SUCCESS = 'FETCH_TASK_COMMENTS_LIST_SUCCESS';
export const FETCH_TASK_COMMENTS_LIST_FAILED = 'FETCH_TASK_COMMENTS_LIST_FAILED';