export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILD = 'FETCH_TASKS_FAILD';

export const FETCH_MY_COMMENTS = 'FETCH_MY_COMMENTS';
export const FETCH_MY_COMMENTS_SUCCESS = 'FETCH_MY_COMMENTS_SUCCESS';
export const FETCH_MY_COMMENTS_FAILD = 'FETCH_MY_COMMENTS_FAILD';

export const FETCH_NEW_COMMENTS = 'FETCH_NEW_COMMENTS';
export const FETCH_NEW_COMMENTS_SUCCESS = 'FETCH_NEW_COMMENTS_SUCCESS';
export const FETCH_NEW_COMMENTS_FAILD = 'FETCH_NEW_COMMENTS_FAILD';

export const FETCH_TARIFS = 'FETCH_TARIFS';
export const FETCH_TARIFS_SUCCESS = 'FETCH_TARIFS_SUCCESS';
export const FETCH_TARIFS_FAILD = 'FETCH_TARIFS_FAILD';