import React from 'react';

import './license-page.scss';

export const LicensePage = () => (
    <div className='license-page__content'>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae assumenda non corporis debitis ad? Animi alias ad est aspernatur optio veritatis libero incidunt, vitae, harum error eos provident modi sapiente aliquid ipsum quibusdam at voluptate perferendis repellendus quae debitis illum sequi quas. Optio voluptatibus veritatis rerum atque ducimus ullam dignissimos vel error earum sed officia, porro aspernatur dolorem voluptate sunt libero, totam, corporis laborum harum reiciendis facere? Vel, eius. Sit quia assumenda doloribus odit, alias deleniti itaque esse qui ut, nulla dicta unde fugiat. Molestias maiores deserunt cumque asperiores! Suscipit earum, dicta a quisquam sequi excepturi itaque reiciendis consectetur obcaecati?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae assumenda non corporis debitis ad? Animi alias ad est aspernatur optio veritatis libero incidunt, vitae, harum error eos provident modi sapiente aliquid ipsum quibusdam at voluptate perferendis repellendus quae debitis illum sequi quas. Optio voluptatibus veritatis rerum atque ducimus ullam dignissimos vel error earum sed officia, porro aspernatur dolorem voluptate sunt libero, totam, corporis laborum harum reiciendis facere? Vel, eius. Sit quia assumenda doloribus odit, alias deleniti itaque esse qui ut, nulla dicta unde fugiat. Molestias maiores deserunt cumque asperiores! Suscipit earum, dicta a quisquam sequi excepturi itaque reiciendis consectetur obcaecati?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae assumenda non corporis debitis ad? Animi alias ad est aspernatur optio veritatis libero incidunt, vitae, harum error eos provident modi sapiente aliquid ipsum quibusdam at voluptate perferendis repellendus quae debitis illum sequi quas. Optio voluptatibus veritatis rerum atque ducimus ullam dignissimos vel error earum sed officia, porro aspernatur dolorem voluptate sunt libero, totam, corporis laborum harum reiciendis facere? Vel, eius. Sit quia assumenda doloribus odit, alias deleniti itaque esse qui ut, nulla dicta unde fugiat. Molestias maiores deserunt cumque asperiores! Suscipit earum, dicta a quisquam sequi excepturi itaque reiciendis consectetur obcaecati?</p>
    </div>
)